### ISSUE TITLE
1 question about code line of 'package intall' part

### ISSUE THREAD

**Issue by jhbae1184** [KanghoonYoon/hetsgg-torch#2]
Thank you for sharing the official code of your paper.
In the package install part you explained, 
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
conda create -n hetsgg python=3.7.7

conda activate hetsgg

conda install -y ipython scipy h5py

pip install ninja yacs cython matplotlib tqdm opencv-python overrides gpustat gitpython ipdb graphviz tensorboardx termcolor scikit-learn==0.23.1

conda install pytorch==1.7.0 torchvision==0.8.0 cudatoolkit=11.0 -c pytorch

pip install torch-scatter==2.0.7 torch-sparse==0.6.9 -f https://data.pyg.org/whl/torch-1.7.0+cu110.html

pip install torch-sparse -f https://data.pyg.org/whl/torch-1.7.0+cu110.html

pip install torch-geometric

git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
python setup.py build_ext install

cd ..

git clone https://github.com/NVIDIA/apex.git
cd apex
pip install -v --disable-pip-version-check --no-cache-dir ./

cd .. (here. if i run here, 'file not exist' error happens. when i skip this line, it works)

python setup.py build develop (is this line for python setup.py in apex, or hetsgg-torch ? latter one has 'RuntimeError: Error compiling objects for extension' )
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

Thank you for good working and look forward to your answer :)

**Comment by jhbae1184** [comment]
Sorry, it is my cuda version problem. Thank you ;)

**Comment by jhbae1184** [comment]
ubuntu 20.04
pytorch 1.8.1
cuda 11.3

**Comment by suexin27** [comment]
hi, I also encountered the same problem. Have you solved it?

**Comment by KanghoonYoon** [comment]
@suexin27 what is your problem? Could you explain in more details?

**Comment by suexin27** [comment]
> @suexin27 what is your problem? Could you explain in more details?

hi, thank you~ I'm running it now, but every time I start validating it in training time, I run into this bug:
<img width="1065" alt="image" src="https://github.com/KanghoonYoon/hetsgg-torch/assets/104906350/63295566-5b03-4f9f-b9ed-629e03c0134e">

**Comment by KanghoonYoon** [comment]
@suexin27 Could you set  the TEST.IMS_PER_BATCH=1? This version of code only supports the one instance in the batch at the validation and testing phase

**Comment by suexin27** [comment]
> @suexin27 Could you set the TEST.IMS_PER_BATCH=1? This version of code only supports the one instance in the batch at the validation and testing phase

thank you！
